name: dingtalk_message
version: 0.0.1
language:
description: Dingtalk message sender
tags:
 - dingding
 - dingtalk
 - message
 - sender

public: true

# clone_in_docker: false

inputs:
  - name: FLOW_DINGTALK_MESSAGE_URL
    editable: true

  - name: FLOW_DINGTALK_MESSAGE_JSON
    editable: true

outputs:

script_path: ./run.sh
